language: "perl"
perl:
  - "5.24"
  - "5.22"

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y ncbi-blast+ emboss embassy-phylip
    - cpanm Test::Pod # optional dependency

install:
    - cpanm -v --installdeps --notest .

script: "perl Build.PL; ./Build test"
